# Route: install | uninstall (default: install)
cilium_action: install

# Helm & Cilium settings (override in group_vars if desired)
cilium_namespace: "cilium"
cilium_chart_repo: "https://helm.cilium.io"
cilium_chart_version: "1.18.1"

# Cluster endpoint + LB IPs (kubeconfig_path comes from group_vars/all/kubeconfig.yaml)
cilium_host: "desktop-server.kubesoar.com"
cilium_load_balancer_ip: "192.168.2.100"
cilium_load_balancer_ip_pools:
  - "192.168.2.64/26"

# Gateway API CRDs (idempotent to apply with state: present)
cilium_gateway_api_crds:
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml"
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml"
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml"
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml"
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml"
  - "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml"

# Values for the Cilium Helm chart
cilium_values:
  kubeProxyReplacement: true
  k8sServiceHost: "{{ cilium_host }}"
  k8sServicePort: 6443
  l2announcements:
    enabled: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  ingressController:
    enabled: true
    default: true
    loadbalancerMode: "shared"
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        io.cilium/lb-ipam-ips: "{{ cilium_load_balancer_ip }}"
      loadBalancerIP: "{{ cilium_load_balancer_ip }}"
    enforceHttps: false

    hostNetwork:
      enabled: true

  gatewayAPI:
    enabled: false
    hostNetwork:
      enabled: true
  envoy:
    enabled: true
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        keepCapNetBindService: true
        envoy:
          - NET_BIND_SERVICE
          - NET_ADMIN
          - SYS_ADMIN
          - BPF

  operator:
    replicas: 1
