---
- name: Install FreeIPA server with DNS using Podman
  hosts: freeipa_host
  become: true
  tasks:

    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Stop dnsmasq service
      service:
        name: dnsmasq
        state: stopped
        enabled: false

    - name: Forcefully kill any remaining dnsmasq processes
      command: killall dnsmasq
      ignore_errors: true

    - name: Check what is using port 53 (Debugging)
      shell: lsof -i :53
      register: port_check_output
      ignore_errors: true

    - name: Fail if port 53 is still in use
      fail:
        msg: "Port 53 is still in use. FreeIPA cannot bind to it."
      when: port_check_output.stdout != ""

    - name: Run FreeIPA server container with automated setup
      shell: |
        podman run -d \
        --name freeipa-server \
        --restart unless-stopped \
        -v freeipa-data:/data \
        -v freeipa-config:/config \
        -p 80:80 \
        -p 443:443 \
        -p 389:389 \
        -p 636:636 \
        -p 88:88 \
        -p 464:464 \
        -p 53:53/tcp \
        -p 53:53/udp \
        --dns=127.0.0.1 \
        -h freeipa.example.com \
        docker.io/freeipa/freeipa-server:almalinux-9-4.11.0 \
        ipa-server-install \
        --realm EXAMPLE.COM \
        --domain example.com \
        --ds-password 'DirectoryManagerPass123' \
        --admin-password 'AdminPass123' \
        --hostname freeipa.example.com \
        --unattended --setup-dns --forwarder 1.1.1.1


    - name: Show the logs if FreeIPA install fails
      shell: |
        podman logs freeipa-server
      register: container_logs
      failed_when: container_logs.stdout.find('Installation failed') != -1

    - name: Debug logs if failed
      debug:
        var: container_logs.stdout
