- name: Setup K3s Single Node Cluster
  hosts: k3s_nodes
  become: true
  gather_facts: false

  tasks:
    - name: Update machine
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s/server/manifests

    - name: Apply K3s configuration template
      ansible.builtin.template:
        src: ../templates/config.yaml.j2
        dest: /etc/rancher/k3s/config.yaml
        mode: '0644'

    - name: Remove any existing manifests
      ansible.builtin.command: rm -rf /var/lib/rancher/k3s/server/manifests/*
      ignore_errors: true

    - name: Copy K3s manifests to server
      ansible.builtin.copy:
        src: "./k3s_manifests/"
        dest: "/var/lib/rancher/k3s/server/manifests"
        mode: '0644'
      when: apply_manifests | default(false)

    - name: Install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
