subscription:
  name: my-tektoncd-operator
  namespace: operators
  channel: alpha
  operatorName: tektoncd-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

tektonConfig:
  deployTektonConfig: true
  name: config
  namespace: tekton-pipelines
  profile: all
  targetNamespace: tekton-pipelines
  pruner:
    resources:
      - pipelinerun
      - taskrun
    keep: 100
    schedule: "0 8 * * *"
  pipeline:
    enableOciBundles: true
  dashboard:
    readonly: false
