bootstrapCluster:
  apps:
    cert-manager:
      enabled: true
      extraManifests:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: cert-manager
            labels:
              istio-injection: "enabled"

      namespace: cert-manager
      metadata:
        name: cert-manager
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd.argoproj.io/sync-wave: "1"
          argocd.argoproj.io/refresh: always
      project: default
      repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.15.3
      helm:
        releaseName: cert-manager
        values:
          crds:
            enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground

    kube-prometheus-stack:
      enabled: true
      namespace: monitoring
      metadata:
        name: kube-prometheus-stack
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd.argoproj.io/sync-wave: "4"
      project: default
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 62.7.0
      helm:
        releaseName: kube-prometheus-stack
        skipCrds: true
        values:
          grafana:
            enabled: true
            ingress:
              enabled: true
              className: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: web
              hosts:
                - "grafana.localhost"

          additionalScrapeConfigs:
            - job_name: prometheus
              static_configs:
                - targets:
                    - localhost:9090
            - job_name: "istiod"
              # Scrape Istiod stats from istio-system namespace
              kubernetes_sd_configs:
                - role: endpoints
                  namespaces:
                    names:
                      - istio-system
              relabel_configs:
                - source_labels:
                    [
                      __meta_kubernetes_service_name,
                      __meta_kubernetes_endpoint_port_name,
                    ]
                  action: keep
                  regex: istiod;http-monitoring
            - job_name: "envoy-stats"
              # Scrape Envoy stats from sidecar and gateway proxies
              metrics_path: /stats/prometheus
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: ".*-envoy-prom"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true

    kube-prometheus-stack-crds:
      enabled: true
      namespace: monitoring
      metadata:
        name: kube-prometheus-stack-crds
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd.argoproj.io/sync-wave: "0"
      project: default
      repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/kube-prometheus-stack/charts/crds
      targetRevision: HEAD
      helm:
        releaseName: kube-prometheus-stack-crds
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
          - ApplyOutOfSyncOnly=true

    awx:
      enabled: true
      namespace: awx
      metadata:
        name: awx-operator
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd.argoproj.io/sync-wave: "2"
          argocd.argoproj.io/refresh: always
      project: default
      repoURL: https://ansible-community.github.io/awx-operator-helm
      chart: awx-operator
      targetRevision: 2.19.0
      helm:
        releaseName: my-awx-operator
        values:
          AWX:
            enabled: true
            spec:
              security_context_settings: {}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
      extraManifests:
        - apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: awx-route
            namespace: awx
            annotations:
              argocd.argoproj.io/sync-wave: "5"
              argocd.argoproj.io/refresh: always
          spec:
            parentRefs:
              - name: traefik-gateway
                namespace: traefik
            hostnames:
              - "awx.localhost"
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: "/"
                backendRefs:
                  - name: awx-service
                    port: 80
    
    rancher:
      enabled: true
      namespace: cattle-system
      metadata:
        name: rancher
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd.argoproj.io/sync-wave: "4"
          argocd.argoproj.io/refresh: always
      project: default
      repoURL: https://releases.rancher.com/server-charts/latest
      chart: rancher
      targetRevision: 2.9.2
      helm:
        releaseName: rancher
        values:
          hostname: rancher.localhost
          ingress:
            enabled: true
            includeDefaultExtraAnnotations: false
            ingressClassName: traefik

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
