---
- name: Install kubectl, helm, and krew locally
  hosts: localhost
  become: true
  tasks:
    - name: Ensure EPEL repository is installed
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Add Kubernetes yum repository for kubectl
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
        mode: '0644'

    - name: Install kubectl
      ansible.builtin.yum:
        name: kubectl
        state: present



    # Krew installation tasks
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Check if krew is already installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.krew/bin/kubectl-krew"
      register: krew_stat

    - name: Install krew (kubectl plugin manager)
      ansible.builtin.shell: |
        set -x; cd "$(mktemp -d)" &&
        OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
        KREW="krew-${OS}_${ARCH}" &&
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
        tar zxvf "${KREW}.tar.gz" &&
        ./"${KREW}" install krew

    - name: Add Krew to PATH in .bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'
        create: yes
        state: present


    - name: Install kubectl ctx plugin using krew
      ansible.builtin.shell: |
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin/$PATH" &&
        kubectl krew install ctx

    - name: Install kubectl ns plugin using krew
      ansible.builtin.shell: |
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin/$PATH" &&
        kubectl krew install ns
