---

- name: Ensure kubeconfig drop-in directory exists (no-op if already present)
  ansible.builtin.file:
    path: "{{ kubeconfig_dropin_dir }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  become: false
  run_once: true

- name: Remove RKE2 kubeconfig from controller
  ansible.builtin.file:
    path: "{{ kubeconfig_path }}"
    state: absent
  delegate_to: localhost
  become: false
  run_once: true
