
{{ if .Values.tektonConfig.deployTektonConfig }}
---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: {{ .Values.tektonConfig.name }}
  namespace: {{ .Values.tektonConfig.namespace }}
spec:
  profile: {{ .Values.tektonConfig.profile }}
  targetNamespace: {{ .Values.tektonConfig.targetNamespace }}
  pruner:
    resources:
    {{ range .Values.tektonConfig.pruner.resources }}
    - {{ . }}
    {{ end }}
    keep: {{ .Values.tektonConfig.pruner.keep }}
    schedule: "{{ .Values.tektonConfig.pruner.schedule }}"
  pipeline:
    enable-tekton-oci-bundles: {{ .Values.tektonConfig.pipeline.enableOciBundles }}
  dashboard:
    readonly: {{ .Values.tektonConfig.dashboard.readonly }}
{{ end }}
