
- name: Restart K3s Node
  hosts: first_master_node:additional_servers:worker_nodes
  become: true
  gather_facts: false

  tasks:
    - name: Restart K3s Service
      ansible.builtin.systemd_service:
        name: k3s
        state: restarted
