---
- name: Ensure Datadog namespace with privileged PSS labels
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ datadog_operator_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: "privileged"
          pod-security.kubernetes.io/audit: "privileged"
          pod-security.kubernetes.io/warn: "privileged"

- name: Delete Kyverno default-deny NetworkPolicy if it exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: absent
    api_version: networking.k8s.io/v1
    kind: NetworkPolicy
    namespace: "{{ datadog_operator_namespace }}"
    name: default-deny-all
  ignore_errors: true

- name: Add Datadog Helm repo
  kubernetes.core.helm_repository:
    name: datadog
    repo_url: "{{ datadog_operator_chart_repo }}"

- name: Install/upgrade Datadog Operator
  kubernetes.core.helm:
    name: datadog-operator
    chart_ref: "{{ datadog_operator_chart_name }}"
    chart_version: "{{ datadog_operator_chart_version | default(omit) }}"
    release_namespace: "{{ datadog_operator_namespace }}"
    create_namespace: false
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    update_repo_cache: true
    atomic: true

- name: Create Datadog secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: datadog-secret
        namespace: "{{ datadog_operator_namespace }}"
      type: Opaque
      stringData:
        api-key: "{{ datadog_operator_api_key }}"
        app-key: "{{ datadog_operator_app_key }}"


- name: Deploy DatadogAgent custom resource
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: datadoghq.com/v2alpha1
      kind: DatadogAgent
      metadata:
        name: datadog
        namespace: "{{ datadog_operator_namespace }}"
      spec: "{{ datadog_operator_agent_spec }}"



