---
# Route based on cilium_action (install | uninstall)

- name: Normalize requested action
  ansible.builtin.set_fact:
    cilium_action_norm: "{{ cilium_action | lower }}"

- name: Validate requested action
  ansible.builtin.assert:
    that: ["cilium_action_norm in ['install','uninstall']"]
    fail_msg: "Invalid cilium_action='{{ cilium_action }}'. Use 'install' or 'uninstall'."

- name: Run uninstall
  ansible.builtin.include_tasks: uninstall.yml
  when: cilium_action_norm == 'uninstall'
  tags: [uninstall]

- name: Run install
  ansible.builtin.include_tasks: install.yml
  when: cilium_action_norm == 'install'
  tags: [install]
