---
- name: Check and display Kubeconfig file content
  hosts: initial_master
  become: true
  tasks:
    - name: Check if Kubeconfig file exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_file

    - name: Fail if Kubeconfig file is missing
      ansible.builtin.fail:
        msg: "Kubeconfig file not found at /etc/rancher/k3s/k3s.yaml"
      when: not kubeconfig_file.stat.exists

    - name: Display Kubeconfig file content
      ansible.builtin.shell: cat /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content
      when: kubeconfig_file.stat.exists

    - name: Output Kubeconfig file content
      ansible.builtin.debug:
        var: kubeconfig_content.stdout
      when: kubeconfig_file.stat.exists
