---
- name: Check and print Kubeconfig file
  hosts: initial_master
  become: true
  tasks:
    - name: Check if Kubeconfig file exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_file

    - name: Fail if Kubeconfig file is missing
      ansible.builtin.fail:
        msg: "Kubeconfig file not found at /etc/rancher/k3s/k3s.yaml"
      when: not kubeconfig_file.stat.exists

    - name: Fetch Kubeconfig file to the local AWX server
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s-kubeconfig.yaml
        flat: yes
      when: kubeconfig_file.stat.exists

    - name: Print the local path to the Kubeconfig file
      ansible.builtin.debug:
        msg: "Kubeconfig file has been copied to /tmp/k3s-kubeconfig.yaml on the AWX server."
