---
- name: Check and print Kubeconfig file
  hosts: initial_master
  become: true
  tasks:
    - name: Check if Kubeconfig file exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_file

    - name: Fail if Kubeconfig file is missing
      ansible.builtin.fail:
        msg: "Kubeconfig file not found at /etc/rancher/k3s/k3s.yaml"
      when: not kubeconfig_file.stat.exists

    - name: Read the Kubeconfig file content
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content
      when: kubeconfig_file.stat.exists

    - name: Output Kubeconfig file content
      ansible.builtin.debug:
        msg: "{{ kubeconfig_content.content | b64decode | to_nice_yaml }}"
      when: kubeconfig_file.stat.exists
