---
- name: Check and fetch Kubeconfig file
  hosts: initial_master
  become: true
  tasks:
    - name: Check if Kubeconfig file exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_file

    - name: Fail if Kubeconfig file is missing
      ansible.builtin.fail:
        msg: "Kubeconfig file not found at /etc/rancher/k3s/k3s.yaml"
      when: not kubeconfig_file.stat.exists

    - name: Fetch Kubeconfig file to local machine
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../k3s-kubeconfig.yaml
        flat: yes
      when: kubeconfig_file.stat.exists