---
- name: Configure K3s worker node
  hosts: workers
  become: true
  vars_files:
    - ../vars.yaml
  tasks:

    - name: Disable Firewall on worker node
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Install K3s agent and join master node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master1']['ansible_host'] }}:6443 K3S_TOKEN={{ token }} sh -