---
- name: Configure K3s worker node
  hosts: workers
  become: true
  vars_files:
    - ../vars.yaml
  tasks:

    - name: Disable Firewall on worker node
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Create K3s configuration directory on worker node
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory

    - name: Configure K3s worker node to join the master
      ansible.builtin.copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          server: https://{{ hostvars['master1']['ansible_host'] }}:6443
          token: {{ token }}
          selinux: true
          debug: true
        force: true

    - name: Install K3s on worker node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
