version: '3'

tasks:

  default:
    description: "Show the help message"
    cmds:
      - task --list-all

  master-build:
    description: "Build the K3s First Server Node"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_create.yaml -e "@vars/k3s-server-node-config.yaml"

  master-restart:
    description: "Restart the K3s First Server Node"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_restart.yaml -e "@vars/k3s-server-node-config.yaml"

  master-clean:
    description: "Clean the K3s First Server Node"

    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_destroy.yaml -e "@vars/k3s-server-node-config.yaml"
  
  master-copy-manifests:
    description: "Copy new manifests and restart K3s on first master"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s-copy-manifests.yaml -e "@vars/k3s-server-node-config.yaml"

  master-add:
    description: "Add Additional K3s Server Nodes"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_add_server.yaml -e "@vars/k3s-server-node-config.yaml"

  worker-build:
    description: "Build the K3s Worker Node"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_worker_node_create.yaml -e "@vars/k3s-server-node-config.yaml"

  worker-clean:
    description: "Clean the K3s Worker Node"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_worker_node_destroy.yaml
  
  kubeconfig-fetch:
    description: "Fetch and Configure K3s Kubeconfig Locally"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/fetch-kubeconfig.yaml

  kubeconfig-delete:
    description: "Delete K3s Kubeconfig Locally"
    cmds:
      - rm -rf ~/.kube

  kubeconfig-delete-cache:
    description: "Delete K3s Kubeconfig Cache Locally"
    cmds:
      - rm -rf ~/.kube/cache