---
# - name: Install RKE2 on servers
#   hosts: rke2_server
#   become: true
#   roles:
#     - rke2_cluster

# - name: Fetch kubeconfig locally
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - role: kubeconfig
#       vars:
#         kubeconfig_action: fetch

# - name: Install Cilium
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - cilium

# - name: Install Kyverno
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - kyverno


# - name: Install cert-manager
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - cert_manager


- name: Install ExternalDNS
  hosts: localhost
  gather_facts: false
  roles:
    - role: external_dns
      vars:
        external_dns_create_cnp: false