---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-default-deny-all-cnp-per-namespace
  annotations:
    policies.kyverno.io/title: Generate Default Deny All (Cilium)
    policies.kyverno.io/category: Sample
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/description: >-
      This policy generates a CiliumNetworkPolicy which denies all ingress and egress
      traffic by default whenever a new namespace is created (excluding system namespaces).
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: generate-cnp-default-deny
      match:
        any:
          - resources:
              kinds: ["Namespace"]
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - kyverno
                - cert-manager
      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: Equals
            value: CREATE
      generate:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        name: default-deny-all
        namespace: "{{ request.object.metadata.name }}"
        synchronize: false
        data:
          spec:
            endpointSelector: {}
            ingress: []
            egress: []
