---
- name: Remove cert-manager completely
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Uninstall cert-manager helm release
      kubernetes.core.helm:
        name: cert-manager
        release_namespace: cert-manager
        state: absent

    - name: Delete cert-manager resources
      kubernetes.core.k8s:
        state: absent
        api_version: "{{ item.apiVersion }}"
        kind: "{{ item.kind }}"
        namespace: "{{ item.namespace | default(omit) }}"
        name: "{{ item.name | default(omit) }}"
      loop:
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
        - apiVersion: cert-manager.io/v1
          kind: Issuer
        - apiVersion: cert-manager.io/v1
          kind: Certificate
        - apiVersion: cert-manager.io/v1
          kind: CertificateRequest
        - apiVersion: acme.cert-manager.io/v1
          kind: Order
        - apiVersion: acme.cert-manager.io/v1
          kind: Challenge

    - name: Delete webhook configurations
      kubernetes.core.k8s:
        state: absent
        api_version: admissionregistration.k8s.io/v1
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
      loop:
        - kind: MutatingWebhookConfiguration
          name: cert-manager-webhook
        - kind: ValidatingWebhookConfiguration
          name: cert-manager-webhook

    - name: Delete CRDs created by cert-manager
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: "{{ item }}"
      loop:
        - certificaterequests.cert-manager.io
        - certificates.cert-manager.io
        - challenges.acme.cert-manager.io
        - clusterissuers.cert-manager.io
        - issuers.cert-manager.io
        - orders.acme.cert-manager.io

    - name: Delete cert-manager namespace
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: cert-manager
