---
- name: Fetch kubeconfig from RKE2 server
  hosts: rke2_server
  become: true
  gather_facts: false
  vars:
    remote_kubeconfig: /etc/rancher/rke2/rke2.yaml
    local_tmp_kubeconfig: "{{ playbook_dir }}/rke2.yaml"
    kube_host: "desktop-server.kubesoar.com"

  tasks:
    - name: Fetch kubeconfig to controller
      ansible.builtin.fetch:
        src: "{{ remote_kubeconfig }}"
        dest: "{{ local_tmp_kubeconfig }}"
        flat: true

    - name: Ensure ~/.kube exists on controller
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
        mode: "0700"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Install kubeconfig to ~/.kube/config (backup if exists)
      ansible.builtin.copy:
        src: "{{ local_tmp_kubeconfig }}"
        dest: "~/.kube/config"
        mode: "0600"
        backup: true
      delegate_to: localhost
      become: false
      run_once: true

    - name: Swap API server to TLS hostname
      ansible.builtin.replace:
        path: "~/.kube/config"
        regexp: 'https://127\.0\.0\.1:6443'
        replace: "https://{{ kube_host }}:6443"
      delegate_to: localhost
      become: false
      run_once: true
